### PR TITLE
Add support for multiple email recipients

### PR DESCRIPTION
**Pull request by Paxa**
This PR solving issue #112

Configuration example:
```
send alerts via email with
  username smtpuser,
  password smtppass,
  smtp_server smtp.mailgun.org,
  to_email "user1@gmail.com, user2@gmail.com",
  from_email app.server@myserver.com
```

I'm new to Go, should this feature have test?

### CODE REVIEW

**Comment by mperham** [comment]
This is by design, not a bug.

**Comment by sorentwo** [comment]
@Paxa: The idea is that you set up an alias or a group to send alerts to. It's easier to configure multiple emails through gmail, or a similar interface, rather than updating N servers with new addresses for notifications.

**Comment by Paxa** [comment]
Why it can not do both?

How to create new group in free gmail account?

In my situation I want to send email to all system administrators and to developer of microservice, I don't want to make many groups just for that purpose

**Comment by Paxa** [comment]
Why it can not do both?

In my situation I want to send email to all system administrators and to developer of microservice, I don't want to make many groups just for that purpose

**Comment by mperham** [comment]
Employees come and go.  Assign ownership of processes to mailing lists, then add/remove employees from those mailing lists.

Inspeqtor is opinionated software and this is one example of an opinion that has been codified.

**Pull request closed without merging**
